#include<Arduino.h>
#include "../include/Sev_Seg.h"

void Segment::begin(type _t){
    this->segment_type = _t;
    for(int i = 0; i < 8; i++){
        pinMode(this->pins[i], OUTPUT);
        (_t == COMMON_CATHODE)? digitalWrite(this->pins[i],HIGH): digitalWrite(this->pins[i],LOW);
    }
}

Segment& Segment::operator=(const Segment& seg){
    if(this != &seg){
        for(int i = 0; i < 8; i++)
        this->pins[i] = seg.pins[i];
    }
    return *this;
}

Segment::Segment(const Segment& seg){
    this->segment_type = seg.segment_type;
    for(int i = 0; i < 8; i++)
        this->pins[i] = seg.pins[i];
}

void Segment::display(int digit){
    if(this->segment_type == COMMON_CATHODE){
    switch(digit){
      case 0: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],LOW);
              break;
      case 1: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 2: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 3: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 4: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 5: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 6: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 7: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 8: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 9:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 10:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 11:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 12:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],LOW);
              break;
      case 13:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 14:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 15: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      default:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
    }
  }
else if(this->segment_type == COMMON_ANODE){
    switch(digit){
      case 0: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 1: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 2: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],LOW);
              break;
      case 3: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],LOW);
              break;
      case 4: digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 5: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 6: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 7: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 8: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 9:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 10:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 11:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 12:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],HIGH);
              break;
      case 13:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],LOW);
              digitalWrite(this->pins[2],LOW);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],LOW);
              break;
      case 14:digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],LOW);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      case 15: digitalWrite(this->pins[0],LOW);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],LOW);
              digitalWrite(this->pins[5],LOW);
              digitalWrite(this->pins[6],LOW);
              break;
      default:digitalWrite(this->pins[0],HIGH);
              digitalWrite(this->pins[1],HIGH);
              digitalWrite(this->pins[2],HIGH);
              digitalWrite(this->pins[3],HIGH);
              digitalWrite(this->pins[4],HIGH);
              digitalWrite(this->pins[5],HIGH);
              digitalWrite(this->pins[6],HIGH);
              break;
    }
  }
}