#include<Arduino.h>
#include "../include/Sev_Seg.h"

void Segment::begin(type _t){
    this->segment_type = _t;
    for(int i = 0; i < 8; i++){
        pinMode(this->pins[i], OUTPUT);
        (_t == COMMON_CATHODE)? digitalWrite(this->pins[i],HIGH): digitalWrite(this->pins[i],LOW);
    }
}

Segment& Segment::operator=(const Segment& seg){
    if(this != &seg){
        for(int i = 0; i < 8; i++)
        this->pins[i] = seg.pins[i];
    }
    return *this;
}

Segment::Segment(const Segment& seg){
    this->segment_type = seg.segment_type;
    for(int i = 0; i < 8; i++)
        this->pins[i] = seg.pins[i];
}

void Segment::display(int display){
    if(this->segment_type == COMMON_CATHODE){
    switch(value){
      case 0: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,LOW);
              break;
      case 1: digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 2: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,HIGH);
              break;
      case 3: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,HIGH);
              break;
      case 4: digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 5: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 6: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 7: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 8: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 9:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 10:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 11:digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 12:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,LOW);
              break;
      case 13:digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,HIGH);
              break;
      case 14:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 15: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      default:digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
    }
  }
else if(type == COMMON_ANODE){
    switch(value){
      case 0: digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,HIGH);
              break;
      case 1: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 2: digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,LOW);
              break;
      case 3: digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,LOW);
              break;
      case 4: digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 5: digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 6: digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 7: digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
      case 8: digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 9:digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 10:digitalWrite(this->a,LOW);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 11:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 12:digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,HIGH);
              break;
      case 13:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,LOW);
              digitalWrite(this->c,LOW);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,LOW);
              break;
      case 14:digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,LOW);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      case 15: digitalWrite(this->a,LOW);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,LOW);
              digitalWrite(this->f,LOW);
              digitalWrite(this->g,LOW);
              break;
      default:digitalWrite(this->a,HIGH);
              digitalWrite(this->b,HIGH);
              digitalWrite(this->c,HIGH);
              digitalWrite(this->d,HIGH);
              digitalWrite(this->e,HIGH);
              digitalWrite(this->f,HIGH);
              digitalWrite(this->g,HIGH);
              break;
    }
  }
}